### PR TITLE
Add `font_size` field to `ThemeContribution` class

### PR DESCRIPTION
**Pull request by dalthviz**
Add `font_size` field to theme contribution definition following changes at napari/napari#5607

### CODE REVIEW

**Comment by GenevieveBuckley** [comment]
Now that https://github.com/napari/napari/pull/5607 is merged, one of the next steps listed is to move this PR out of draft status ([see comment](https://github.com/napari/napari/pull/5607#issuecomment-1634432213)). What needs to happen to facilitate that?

**Comment by dalthviz** [comment]
I think the missing thing was to merge https://github.com/napari/napari/pull/5607. Will update this to get the latest changes on main and mark it as ready for review if checks pass :+1:

**Review by nclack — APPROVED** [review]
lgtm! Thanks

**Comment by GenevieveBuckley** [comment]
Thanks @dalthviz 🎉

**Pull request merged**
