### PR TITLE
DOC Add cross references to widget contributions

### PR DESCRIPTION
**Pull request by lucyleeow**
Depends on https://github.com/napari/docs/pull/286 

Adds references to new 'creating widgets' section and gallery and cookiecutter to widget contributions page.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
You can edit OP with 
Depends on
To make the CI action check it.

**Comment by psobolewskiPhD** [comment]
Ha! I got my repos confused. This one doesn't have the action to check for dependency between PR.

**Comment by lucyleeow** [comment]
@psobolewskiPhD  I think this is ready for review now that the dependency has been merged :pray: Thank you!

**Review by DragaDoncila — APPROVED** [review]
Awesome, thanks @lucyleeow

**Pull request merged**
