### PR TITLE
Add `npe2 list` command to discover/display all currently installed plugins

### PR DESCRIPTION
**Pull request by tlambert03**
work in progress, but here's the idea:

Screen Shot 2022-06-21 at 9 08 15 PM

### CODE REVIEW

**Comment by nclack** [comment]
I find myself using this constantly bwiw

**Comment by tlambert03** [comment]
> I find myself using this constantly fwiw.

what do you mean?  Like, you check out this branch and run it? 😂 if so we need to get this in for you :)

> will need `rich` in the `install_requires`?

Yep, will do thanks.

**Comment by tlambert03** [comment]
Ok, need to add tests and more docs, but i think the implementation is roughly where I'd have it, so marking ready for first review.  I added an optional `--format` flag. 

Screen Shot 2022-06-24 at 8 02 23 AM

Screen Shot 2022-06-24 at 8 02 42 AM

Screen Shot 2022-06-24 at 8 02 54 AM

**Comment by tlambert03** [comment]
I've merged in #197 here, so that should be reviewed first.  I also added docs and cleaned this up a bit.  So the only thing left now is to complete test coverge

**Review by nclack — APPROVED** [review]
Thanks.  Looks great.

**Pull request merged**
