### PR TITLE
Make `npe2 convert` modify a repository

### PR DESCRIPTION
**Pull request by tlambert03**
This is to address https://github.com/napari/npe2/issues/59

currently `npe2 convert` expects an npe1 plugin name, and outputs a manifest to stdout, or to whatever name the user gives for the `--out` flag.

That still leaves the user with some work to do: putting the file in the top level module, and modifying entry points in `setup_cfg`.  this PR turns `convert` into an actual repo conversion.  To get the old behavior of just printing the manifest use `npe2 convert . --just-print`  (but note, it still takes a patch now, and not a package name).

This doesn't eliminate the need for the path to be an _installed_ package in the current repository.  So this will only work if the path being provided points to a package installed in the current environment.  It's hard to get around this, since npe1 _has_ to import in order todetect all the contributions.

### CODE REVIEW

**Comment by nclack** [comment]
@tlambert03 What's the status here?  It looks like there's a related commit on main that should go here.

I really love this.  It's very convenient and seems to work pretty well on my system. 

some notes from running it:
 - it feels like it should be an opt-in/safe-mode before files are written. something like `git clean -n`
 - the old lookup-by-name option might be nice to have around?  I can't think of why though. so just mentioning.

**Comment by tlambert03** [comment]
> @tlambert03 What's the status here? It looks like there's a related commit on main that should go here.

it's close 

> * it feels like it should be an opt-in/safe-mode before files are written. something like `git clean -n`

by default?  or only if you add the dry-run flag?  (my preference is to modify by default.  It's only adding a new file, and making a one-line modification to setup.cfg.  I can add something to the cli help string (i think the word "convert" does imply that we're modifying too)

> * the old lookup-by-name option might be nice to have around?  I can't think of why though. so just mentioning.

agreed, that's one thing I'm trying to bring back before merge

**Comment by nclack** [comment]
> add the dry-run flag

this one. basically just print out the files that will get modified.

**Comment by tlambert03** [comment]
ok, I think this is ready enough to merge.  the workflow still shows that a number of plugins fail, but i think it's mostly on the plugin side of things.  turned off the workflow for now

**Comment by tlambert03** [comment]
@nclack  feel free to merge when you want.  current cli is 

```
npe2 convert .  # turn current directory  into new style plugin (it MUST also be installed in current env)
npe2 convert some-package  # print out manifest for some-package
npe2 convert -n .  # dry run for convert
```

**Comment by nclack** [comment]
Ran into a problem.  When make build and install the bdist of the converted package and try to run napari I get this:

```
napari.manifest -> 'napari_animation:napari.yaml' could not be imported: Could not find file 'napari.yaml' in module 'napari_animation'
```

It looks like napari.yaml is not begin placed in the root module folder. It looks like setup.cfg is also missing 

```ini
[options.package_data]
napari_animation =
    napari.yaml
```

If I move the `napari.yaml` into `napari_animation` and add the package_data thing, then it works.

**Comment by tlambert03** [comment]
Ah right! Good catch thanks, will fix

**Comment by tlambert03** [comment]
fixed, will merge after tests pass

**Pull request merged**
