### PR TITLE
Fix a few broken links

### PR DESCRIPTION
**Pull request by melissawm**
Addresses https://github.com/napari/napari/issues/2274 by fixing a few broken links in the npe2 documentation.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@melissawm The anchors arn't working for me. For example the IO anchor just takes me to the top of npe1.html
The link from the actual anchor is:
https://napari.org/stable/plugins/npe1.html#single-layers-io
Am I doing it wrong? or do these links need the `stable/` added (in this new place) to avoid the redirect?

**Comment by melissawm** [comment]
Ah yes - I tested those locally and forgot about the redirect. Let me fix this, thanks for the heads up!

**Comment by melissawm** [comment]
Should be good to go now!

**Review by psobolewskiPhD — APPROVED** [review]
Hmm, I don't have permissions to re-run CI or merge 😢 
But the links work 😊

**Review by nclack — APPROVED** [review]
thanks!

**Pull request merged**
